spring.application.name=moviebooking

# PostgreSQL DataSource
# spring.datasource.url=jdbc:postgresql://localhost:5432/rkdb
# spring.datasource.username=postgres
# spring.datasource.password=rama
# spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# JWT
app.jwt.secret=movie_booking_super_secret_key_for_jwt_2024_very_long_secure_string
app.jwt.expiration=86400000

# CORS
# app.cors.allowed-origins=http://localhost:8080
app.cors.allowed-origins=https://rk-demo.onrender.com

spring.datasource.url=postgresql://rkdb_aa89_user:HOFpuZ2S5R860XQUcnjH0uckEHOIdxTu@dpg-d7cd1urbc2fs73eguag0-a.oregon-postgres.render.com/rkdb_aa89
spring.datasource.username=rkdb_aa89_user
spring.datasource.password = HOFpuZ2S5R860XQUcnjH0uckEHOIdxTu
spring.datasource.driver-class-name=org.postgresql.Driver